### ISSUE TITLE
Create User Docs

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-ckan-registry#109]
Place holder issue to define the areas that need user docs.

- [x] Overview of the CKAN Registry Page type
- [x] Common CKAN/Dataset format
- [x] Adding a dataset/resource
- [x] Editing columns
- [x] Creating filters, plus a note to the filter 
- [x] Describe how information is displayed on the frontend
- [x] ...

**Comment by brynwhyman** [comment]
Remember to follow the style guide from confluence.

**Comment by ScopeyNZ** [comment]
There's also the user guide/docs/help on elemental that's a good reference point 🙂

**Comment by robbieaverill** [comment]
PR is merged, follow up PRs welcome. There's two outstanding screenshot requests which would be good to do at some point when @NightJar has 5 minutes spare.
