### ISSUE TITLE
Add underline to "Try again?" in error notice for PresentedOptions component

### ISSUE THREAD

**Issue by NightJar** [silverstripe/silverstripe-ckan-registry#118]
As a follow up https://github.com/silverstripe/silverstripe-ckan-registry/pull/69#issuecomment-453251308  the link is missing an underline.

We should add `text-decoration: underline` to the following rule:

https://github.com/silverstripe/silverstripe-ckan-registry/blob/892db0517bdb76e84c1f9ca9b153f5f37ae35de3/client/src/components/CKANPresentedOptionsField.scss#L45-L47

**Comment by robbieaverill** [comment]
Is that the only change required? If so, feel like making a super quick PR to do it?

**Comment by robbieaverill** [comment]
I realised the slight irony in what I just posted.

https://github.com/silverstripe/silverstripe-ckan-registry/pull/125 - untested, but if that's all you want then there it is
