### ISSUE TITLE
TODO: Checks for changes to data structure

### ISSUE THREAD

**Issue by rupachup** [silverstripe/silverstripe-ckan-registry#13]
### Acceptance criteria

* TBC - we need to flesh this out more first

### Notes
- for first version we'll just tell users that they'll need to be aware of this stuff. so a human rather than tech fix
- wont do this for first version

**Comment by robbieaverill** [comment]
We have an alert message that pops up when you change the dataset URL now, I think we can close this (especially since it's not a complete story)
