### ISSUE TITLE
Prepare data models for Elemental use

### ISSUE THREAD

**Issue by NightJar** [silverstripe/silverstripe-ckan-registry#134]
As an "get up and go" appraoch we've structured this module around showing data on a Page. However as content authors increasingly (hopefully) move towards [Elemental](https://github.com/dnadesign/silverstripe-elemental) adoption we should tidy the spread of information and consolidate it where it makes sense.

To this end I propose:
- Move `getCKANCllientConfig` from `CKANRegistryPageController` onto the `Resource` model, as it is effectively a representation of the data there on out.
- Move `ItemsPerPage` from `CKANRegistryPage` Settings tab onto the `Resource` model, as it too is used in representing the data returned via the configuration returned by that model, and is more closely related to it than the Page.

This will allow an Element to have all the information it needs to render the same configuration (and perhaps the same front end React components) required to render the data returned from a CKAN API.

**Comment by GuySartorelli** [comment]
This is no longer a supported module so we aren't likely to implement this change. If someone is keen for this and wants to put in the work to implement it, check the CMS 5.0.0 changelog for instructions for how to get in touch about maintaining old modules.
