### ISSUE TITLE
Readable label logic for values with slashes and spaces around them

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-ckan-registry#138]
Input: `Town / City`

Expected: `Town/City`

Actual: `Town  city`

I don't think we should worry much about the lowercase c in city here, `Town/city` would be fine and `Town/City` would be fine too IMO.

**Comment by robbieaverill** [comment]
PR: https://github.com/silverstripe/silverstripe-ckan-registry/pull/191

**Comment by ScopeyNZ** [comment]
Merged. If we wanted to follow up with the capitalisation we could do something like:

```
preg_replace_callback('#\s/|/\s(.)#', function($matches) { 
    if (!empty($matches[1])) {
        return strtoupper($matches[1]);
    }
    return '';
}, $input);
```

**Comment by robbieaverill** [comment]
I prefer it without, personally - I'm not really that bothered about it though
