### ISSUE TITLE
Dev Docs

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-ckan-registry#140]
A list that may need adding to:
- [x] Explain that the frontend display was purposefully built with a de-coupled approach in mind. The React app that we have built is an _example_ of how it can be implemented in the frontend that people can build upon, or take as an example if they want to use a different front-end library
- [x] Note that the filters are using the CKAN SQL endpoint - data.govt should have this enabled for all datasets but we should make a note that this won't always be the case according to the CKAN spec.
- [x] Overview in readme
- [x] BEM class naming convention
- [x] React component architecture in the CMS

**Comment by robbieaverill** [comment]
PR at https://github.com/silverstripe/silverstripe-ckan-registry/pull/158
