### ISSUE TITLE
Column results conditions reflected in front-end

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-ckan-registry#141]
Built in #23, this needs to be tied to pre-filter data populated into the CKAN registry table by default.

It should be be used to update the select statement, using the CKAN SQL endpoint, which is updated with a javascript function.

**Comment by robbieaverill** [comment]
Example use case: I select the "City" column and add a filter that says "value must match 'Auckland'" so I can show a list of Auckland health clinics.

**Comment by robbieaverill** [comment]
So our options in the CMS are "must match" and "must not match". The SQL query JS API we've written always does a "like" check which would match `Not-Auckland` as a value. I may need to adjust this to make the "like" `%` wrappers configurable

**Comment by robbieaverill** [comment]
PR at https://github.com/silverstripe/silverstripe-ckan-registry/pull/157
