### ISSUE TITLE
Edit column to filter by distinct - implement

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-ckan-registry#142]
When editing a column, there is the option to "Only show one value if duplicates exist'.

Currently this checkbox has no functionality. It should be be used to add a distinct select statement, using the CKAN SQL endpoint, which is updated with a javascript function. 

@ScopeyNZ has recently been working with the SQL endpoint and could have further detail.

**Comment by robbieaverill** [comment]
@ScopeyNZ there's no linked issues here, did #160 fix this?

**Comment by ScopeyNZ** [comment]
Yes it did. Thanks for chasing.
