### ISSUE TITLE
Use the page title on the frontend instead of dataset + resource name

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-ckan-registry#144]
By default, the frontend will display a heading of the data source / resource name as `ckan-registry_title` i.e 'Family Services Directory / Tasman'.

Functionality could be added to the CMS to allow a content editor to edit the title that's displayed on the front-end. Examples where they might want to change it, are:
- Where the resource name is not in a friendly format by default

_Note: I've assumed the title should always be present, so there's no option to remove it completely. This is open to feedback_

**Comment by robbieaverill** [comment]
@camfindlay suggested yesterday that we could use the CMS page title instead of generating it from the dataset and resource name. I added the latter because we didn't have anything else, but if we're going to use the page title that's an easy change. Thoughts @brynwhyman?

**Comment by camfindlay** [comment]
See the orignal ACs, was always supposed to be page title and content.

**Comment by camfindlay** [comment]
Use case example, I might set up a pre-filtered register of something in which case I'll want to be able to name the landing page appropriately.

**Comment by robbieaverill** [comment]
Ok this was fixed already with eb4d6dfaf36a5a202677afc8045ce055657903d8
