### ISSUE TITLE
A dataset does not populate in CMS when first added

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-ckan-registry#146]
Looks like a bug.
**Recreate by:**

1. create a new CKAN Registry Page
2. add a dataset
3. save the page
4. observe that the data and columns does not load in the CMS

**Expected behaviour:**
On Save, the CMS gridfield should refresh and display the CKAN data.

**Note:**
A refresh of the page will display the data.

**Comment by robbieaverill** [comment]
@brynwhyman I can't reproduce this on the latest head of master. Would you mind trying again? If it's still happening for you, can you check if there are any browser console error messages or failed network requests happening?

**Comment by brynwhyman** [comment]
I can still reproduce but will accept it's an issue with my project code. No console errors are appearing. Happy to close given you cannot reproduce.
