### ISSUE TITLE
Search interface is good on mobile

### ISSUE THREAD

**Issue by rupachup** [silverstripe/silverstripe-ckan-registry#15]
## User story
As a register search user viewing on mobile
I can use the interface and return usable results
So that I can interact with the data on the go.

## Acceptance criteria

- [ ] UI/layout of the keyword input, filter elements, results etc is considered.
- [ ] Mobile is as easy to use as desktop and does overly degrade the experience.

### Notes:

- Should be part of overall Definition of done for this work

**Comment by robbieaverill** [comment]
I suggest we close this - this should be an acceptance criterion for the "make a search form" ticket

**Comment by ScopeyNZ** [comment]
Yep these are really more to capture the "Definition of Done".
