### ISSUE TITLE
Default filter searches only first column, not all columns

### ISSUE THREAD

**Issue by NightJar** [silverstripe/silverstripe-ckan-registry#153]
When a user creates a CKAN Registry Page and sets up a data set for the first time, a default filter is added which is a simple string input that is intended to search all fields.

However upon testing, this only searches the first column in the results table.

E.g. the data set here is "[Family Services Directory - Auckland](https://catalogue.data.govt.nz/dataset/family-services-directory/resource/496d2b91-2e9a-4e72-9c07-cf41141aefa6)" - **All** the results (of which there are 145 at the time of testing) have their `Physical region` in Auckland.
But searching "auckland" only returns those who's names have Auckland in them (of which there are 7).

![image](https://user-images.githubusercontent.com/778003/51643417-42bfc200-1fd1-11e9-8093-54927be39a35.png)

**Comment by robbieaverill** [comment]
So when the default filter is created it has "All columns" checked, which indicates that the search term should be applied to all of the columns. This does sound like a bug =)

**Comment by NightJar** [comment]
Yes, it also has the implication that `All columns` would fail for all other filters created too :/

**Comment by camfindlay** [comment]
Also... is it all visible columns? Or all columns in the underlying dataset? I'm hoping for the later but the former would be enough for now.

**Comment by robbieaverill** [comment]
I can't reproduce this with `1.0.x-dev` 10644fd1c780e96b17ddfecfe9064dfd24f1d22c. When I filter or don't filter that dataset by "Auckland" on the default filter, it has the same number of pages and same records.

**Comment by robbieaverill** [comment]
@camfindlay currently it filters on the visible columns in the results view. I think it'd be reasonable to filter on records by columns that are visible in detail view but not in results view, not sure about filtering on entirely invisible columns... Shall we raise a new issue for it anyway?

**Comment by ScopeyNZ** [comment]
I feel like I spoke to someone about this but maybe I'm imagining things. When it was added we/I felt that getting results back that didn't seem to have anything to do with the search term felt a little strange. For example "Youth" could match some random column in the dataset that stores whole paragraphs of content.
