### ISSUE TITLE
Archiving a page causes an error

### ISSUE THREAD

**Issue by NightJar** [silverstripe/silverstripe-ckan-registry#159]
Slightly misleading title, please forgive.

Steps to recreate:

4.3.x-dev project, `silverstripe/ckan-registry` installed, on [current `dev-master`](https://github.com/silverstripe/silverstripe-ckan-registry/tree/bc06361b8e98ac1098c91ba7b5c1525b6d3161ee) (bc06361b8)
- Log in to CMS
- Create CKAN Registry Page
- Fill it with data (e.g. [Auckland family services](https://catalogue.data.govt.nz/dataset/family-services-directory/resource/496d2b91-2e9a-4e72-9c07-cf41141aefa6))
- Save and publish
- Reload page
- Select "more options" three dots next to publish button
- Click "Unpublish and archive"A
- Wait for loading to complete
- Refresh page (F5/Ctrl+R/Cmd+r)
- Observe `nl2br` error about expecting a string, getting an array.

Tested with `composer create-project silverstripe/installer cmsarchiveandrefreshbug 4.3.x-dev` and could not reproduce (attempting to `Unpublish & archive` the "Contact us" page). This indicates one of two things to me:
1. The issue is with this module
2. The issue is with any page that has a react rendered form field on it

Unsure which, maybe neither. Logged issue here.

**Comment by NightJar** [comment]
Ah. 👍

**Comment by brynwhyman** [comment]
@clarkepaul, @sachajudd  we'll need some designs for a readonly state of the gridfield. We're happy to start this on our own, but keen to run this past you. We're looking to bring this into our upcoming sprint, so ping one of us when you see this.

**Comment by brynwhyman** [comment]
All components need a read only state, preferably in react.

**Comment by clarkepaul** [comment]
Cool, we already have something for this regarding GridField, need to get it uploaded to our style guides. Will let you know when its uploaded. For GridField its basically the background colour change and the actions at the end are dependant on what can be done in a readonly state.

**Comment by robbieaverill** [comment]
@clarkepaul yeah we're talking mostly about the "Presented options" field and the "Result conditions" field. We can make best guesses as to what you'll expect (e.g. exactly what's there except it's disabled) but would be cool to get you to eyeball it beforehand in case you disagree

**Comment by ScopeyNZ** [comment]
PR at #198
