### ISSUE TITLE
Show nothing if no "In Results" are checked

### ISSUE THREAD

**Issue by NightJar** [silverstripe/silverstripe-ckan-registry#161]
At current if an editor sets up a page for CKAN, selecting a resource but doing no further configuration, a table results with the columns `Id` and `griddleKey`, both of which are just sequential numbers.

![image](https://user-images.githubusercontent.com/778003/52022791-52a24d80-255f-11e9-8e68-456df139db63.png)

If no columns have been chosen to show, the entire interface should not display on the front end.

**Comment by robbieaverill** [comment]
@sachajudd any ideas what we should display instead?

**Comment by ScopeyNZ** [comment]
We spoke about this offline and forgot to relay it here 😨 .

IIRC @sachajudd suggested we show the "No Results" like we have when there is nothing that matches your search query.

**Comment by robbieaverill** [comment]
There's not much point in providing filters that can't be used - maybe we should just hide them?

**Comment by robbieaverill** [comment]
Looks like there's actually code for this already, it's just a regression since we always add _id field now

**Comment by robbieaverill** [comment]
PR at https://github.com/silverstripe/silverstripe-ckan-registry/pull/197

**Comment by ScopeyNZ** [comment]
Closed with #197
