### ISSUE TITLE
Search and Clear buttons need more space at narrow widths

### ISSUE THREAD

**Issue by NightJar** [silverstripe/silverstripe-ckan-registry#162]
When viewing the front-end of a CKAN Registry page, the filter section shows to the left of the results table.
When viewing the site at a narrow width, filters sit above the results table.

However when viewing the site at a point where it is narrow, but not narrow enough to trigger the responsive breakpoint, then the search and clear buttons stack on top of each other, with no spacing.

![image](https://user-images.githubusercontent.com/778003/52025628-f55fc980-2569-11e9-8ad1-f6462192992c.png)

They should at least have equal spacing as when they are presented side by side.
![image](https://user-images.githubusercontent.com/778003/52025649-0c062080-256a-11e9-8de1-0cc3e49628d6.png)

Agreed, @sachajudd ?

**Comment by robbieaverill** [comment]
PR at #186
