### ISSUE TITLE
Adjust "Dropdown options" - "Select from all options" to handle long labels

### ISSUE THREAD

**Issue by NightJar** [silverstripe/silverstripe-ckan-registry#164]
![image](https://user-images.githubusercontent.com/778003/52077944-030f6080-25f7-11e9-8822-f9a89c95f881.png)

In the screenshot above we can see two options available that have labels longer than there is space in the container, causing them to wrap (correct behaviour). However when they wrap they also seem to push down 2/3rds of a line so they are then not sitting in-line with their corresponding checkbox.

**Comment by robbieaverill** [comment]
PR at https://github.com/silverstripe/silverstripe-ckan-registry/pull/190

**Comment by ScopeyNZ** [comment]
Closed in #190
