### ISSUE TITLE
Re-add default filter 'Search' label

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-ckan-registry#167]
Revert #123 & #124 so that the the default test filter has a label of 'Search' - as per #96 

cc @sachajudd @clarkepaul is this what you're after?

**Comment by clarkepaul** [comment]
Yeah as long as the field as a label I'm happy, otherwise it wouldn't pass accessibility tests.

**Comment by ScopeyNZ** [comment]
Added a commit that resolves this in #174
