### ISSUE TITLE
Add front end config to Dev Docs

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-ckan-registry#171]
For those wanting to build their own front end app, there could be more information in the dev docs to explain the existing configuration and how this should be edited if a developer want to tweak/create the front end display.

@ScopeyNZ / @NightJar can you please elaborate if necessary

**Comment by robbieaverill** [comment]
More so than what we have currently in https://github.com/silverstripe/silverstripe-ckan-registry/blob/master/docs/en/frontend.md?

**Comment by brynwhyman** [comment]
> More so than what we have currently in https://github.com/silverstripe/silverstripe-ckan-registry/blob/master/docs/en/frontend.md?

I raised this issue after a conversation in the recent demo. It looks to me like there's enough information too. 

@ScopeyNZ / @NightJar can you please confirm if you see anything else as required here?

**Comment by NightJar** [comment]
The documentation linked gives an intro to the example app, and talks about modifying that by copying it, etc. or configuring the React components involved.

The issue raised in demo was more about building a brand new front-end from scratch - what does a developer need to know about what configuration info is exposed to the front-end, can they configure/extend that, how do they trigger it, and how they can consume it?

E.g. the Include template with the JSON blob on it in our example
What does that JSON blob look like as a schema
What are the options for, what is their intent
Can custom options be injected into this blob

**Comment by robbieaverill** [comment]
>E.g. the Include template with the JSON blob on it in our example

This is an MVP approach that I don't think we should solidify in documentation. We need to expose it via a GET endpoint on a controller somewhere instead (like FormSchema).

>What does that JSON blob look like as a schema

I think that documenting the schema would just create maintenance burden for us. Developers can work it out pretty easily by looking at it (IMO). Perhaps we could show excerpts of it with a note saying "please note that this is an example and you should check the output of your schema before implementing a frontend client" or something

>What are the options for, what is their intent

I would've thought that existing documentation should cover that, we don't need to do this separately for the frontend example app documentation?

>Can custom options be injected into this blob

As with most SilverStripe code, this can be achieved with extensions. I think the code is pretty self documenting at this point and I'm generally against adding tautological documentation

**Comment by NightJar** [comment]
>This is an MVP approach that I don't think we should solidify in documentation

I think documentation is not a solid thing, just as the code it describes isn't. As features are added, so are the docs updated to reflect that. I think this is true of the first two points, to an extent. A full schema probably isn't what's really needed, just more a guide... 🤷‍♂️ You're right in that the things it exposes are documented elsewhere.

To that end I see merit in your latter two points, but simply mentioning that more detailed info can be found elsewhere also has merit. People reading such docs may not be confident SilverStripe developers, and this may be the first document they read (which in turn can lead to more involved core concepts), not necessarily the other way around.

The documentation desired here need not be detailed, a loose guide on "where to start" is essentially all that was requested by @camfindlay (who may be able to describe this with better context than I can).

**Comment by camfindlay** [comment]
Assume someone has some React skills and has never touched SilverStripe. What's the minimum you could tell them about how SilverStripe works in order for them to get how to plug in their own React frontend. So as @NightJar says, the "where do I start" is enough. Then let's hope they start peaking under the hood of SilverStripe enough to get more involved in the community :D

**Comment by ScopeyNZ** [comment]
I think we can just show and explain these LOCs:

https://github.com/silverstripe/silverstripe-ckan-registry/blob/master/templates/Includes/CKANRegistry.ss#L1-L3

That should be enough.

**Comment by robbieaverill** [comment]
Yeah, I still think we should make this an API endpoint fetch for the schema before we stabilise and document the process, but if we don't get time to do that then I agree that would be enough too

**Comment by robbieaverill** [comment]
I've made a PR to decouple the schema fetching and have added some extra documentation around either fetching or injecting it into the frontend application, see #182
