### ISSUE TITLE
Filter broken with pagination

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-ckan-registry#172]
It appears the filters won't work if you search on a page that is not the first.

To recreate:
1. Create a page with a dataset, publish
2. On the site, navigate to the second page of a table
3. Search for a piece of text you know is in the data with the text filter
4. Observe 'No results found; message

Running `dev-master 82989a9`

Looks like there's related filter issues here #153 

We should ensure that when filtering, you are returned to page 1

**Comment by brynwhyman** [comment]
Check that #145 is merged before looking at this

**Comment by ScopeyNZ** [comment]
Included in #173

**Comment by robbieaverill** [comment]
Fixed with #173
