### ISSUE TITLE
Deselecting "Select from all options" makes checkboxes disappear

### ISSUE THREAD

**Issue by sachajudd** [silverstripe/silverstripe-ckan-registry#179]
I can't exactly remember what we decided when deselecting the checkboxes (if they stay where they are or move to the top of the list). We could leave them where they are and have a "re/deselect all" see #100. For now I think they should move to the top 🤔 cc @ScopeyNZ 

![deselect](https://user-images.githubusercontent.com/24258161/52372245-867bf680-2abc-11e9-9e29-11d4a489bcfa.gif)

**Comment by robbieaverill** [comment]
I can't reproduce this on the latest 1.0 branch. For me the checkboxes stay where they were, just unselected. Could you please try again and see if the issue still exists for you?

**Comment by ScopeyNZ** [comment]
Try adding a dropdown and deselecting items before you save it.

**Comment by robbieaverill** [comment]
Ah yep, so this only happens before you've saved the filter - thanks

**Comment by robbieaverill** [comment]
In light of that, I guess it should behave the same as it does after it has been initially saved - keep them in the list in their original position, but unchecked

**Comment by ScopeyNZ** [comment]
I agree. I think re-ordering un-selected options would classify as a follow up issue if required.

I'm guessing it's something to do with initial state of the _value_ of the field too.

**Comment by robbieaverill** [comment]
Can also be reproduced by changing the Column source(s) field before saving a previously saved filter again

**Comment by ScopeyNZ** [comment]
I managed to discover the cause and fix this in #198 .
