### ISSUE TITLE
Populate/repopulate list of columns available for the page's resource when saving the URL and resource

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-ckan-registry#18]
Given that #17 is implemented, when the page is saved with a changed/new resource URL/ID specified, we need to clear and re-populate the associated "columns", which are displayed in a GridField later.

* Clear existing columns
* Populate new columns from the resource API result
* Don't care about versioning for now
* If possible we could update deltas on the columns rather than purge and recreate, but only if it's quick

**Comment by brynwhyman** [comment]
> Clear existing columns
Done as part of the model already?

**Comment by brynwhyman** [comment]
We shouldn't worry about the API call failing as part of this. That's been split into #34

**Comment by robbieaverill** [comment]
Yep, the "clear" part is already in place. It's just the re-populating to be done now

**Comment by robbieaverill** [comment]
I've just given the PR at #41 a test. I've made two hotfixes: https://github.com/silverstripe/silverstripe-ckan-registry/commit/409fa82e89ec4889094582eea4c6683021ac879b and https://github.com/silverstripe/silverstripe-ckan-registry/commit/b56d67303ccecd0eb45d7de7e83deeaf1fd59b1e. It's working nicely now, although the "Order" value is not being set, everything is zero. I'll make a separate PR to address that.

**Comment by robbieaverill** [comment]
PR at #42
