### ISSUE TITLE
CMS configured filter sort order not reflected in the frontend React app

### ISSUE THREAD

**Issue by camfindlay** [silverstripe/silverstripe-ckan-registry#180]
When you start adding multiple filters in the CMS and then reorder them, this new order is not reflected in the frontend React app.

**PR:** https://github.com/silverstripe/silverstripe-ckan-registry/pull/183

**Comment by robbieaverill** [comment]
PR at https://github.com/silverstripe/silverstripe-ckan-registry/pull/183
