### ISSUE TITLE
Create "CKANDataColumn" model and GridField view for display on CKANRegistryPage

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-ckan-registry#20]
Will likely be attached as a `has_many` on [CKANRegistryPage](https://github.com/silverstripe/silverstripe-ckan-registry/issues/19).

A column represents one of the columns from a CKAN result set. They will be displayed in a GridField on a CKANRegistryPage and will allow the CMS user to control which columns from a data set are displayed on the frontend to users.

Fields:

* Original label (text)
* Readable label (text: original label with underscores removed, converted to sensible English casing)
* Type (e.g. numeric, text etc)
* In results (bool) (inline editable in GridField)
* In detail (bool) (inline editable in GridField)
* Filter duplicates (bool) "only show one value if duplicates exist"
* Sort order (int)
* Result conditions (json blob?)

Notes for CMS Fields:

* Visibility: composite checkbox field for "in results", "in detail" and "only show one value if duplicates exist"

Example GridField view from designs:

[Styleguide](https://projects.invisionapp.com/dsm/silver-stripe/silver-stripe/asset/components/5bc3cd2e846a5a0011026c0c)

Example popup showing the rest of the fields for each model in a modal:

[Styleguide](https://projects.invisionapp.com/dsm/silver-stripe/silver-stripe/asset/components/5bc3cd2e846a5a0011026c0e)

**Comment by NightJar** [comment]
PR addresses all but styling (which can be followed up on later) in #36
Styling is a little in flux in that the product owner is not super stressed about modals, although the designs call for them, etc. Thus a merge here would be far more ideal to let work continue elsewhere while styles and non-functional requirements are met in a follow up issue: #??

**Comment by robbieaverill** [comment]
We have a separate issue for the necessary tasks to do the modals (form builder implementation, factory etc)

**Comment by NightJar** [comment]
I think that we should close this on the recent directive from the Product Owner that "functional software is better than nice looking half-done software" (paraphrased). What say you @brynwhyman? :)

**Comment by robbieaverill** [comment]
Reopen if necessary
