### ISSUE TITLE
Resource locator field fails in IE 11 with resource-specific URLs

### ISSUE THREAD

**Issue by Cheddam** [silverstripe/silverstripe-ckan-registry#219]
**Tested in:** Silverstripe CMS `4.5.0-rc1`, CKAN Registry `1.1.1`
**Example URL:** https://catalogue.data.govt.nz/dataset/family-services-directory/resource/496d2b91-2e9a-4e72-9c07-cf41141aefa6

In Chrome, entering this URL in the Data source URL field results in a successful parse and population of the available resources. In IE 11, the load fails with the following console error:

```
Unhandled promise rejection TypeError: Object doesn't support property or method 'lastIndexOf'
```

Unsure if related, but I also get the following console error any time a CKAN Registry Page is loaded in the CMS in IE 11:

```
Object doesn't support property or method 'from' - bundle.js (1,24015)
```

**Comment by robbieaverill** [comment]
Good thing we did a whole bunch of IE11 testing during development eh

**Comment by emteknetnz** [comment]
IE11 is no longer supported https://forum.silverstripe.org/t/phasing-out-cms-support-for-ie11/4410
