### ISSUE TITLE
Add filter conditions React component for data column detail form

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-ckan-registry#23]
Requires #20 

~Will be rendered in [the modal popup for a DataColumn's details](https://github.com/silverstripe/silverstripe-ckan-registry/issues/22)~ 

AC:
- A single dropdown between 'must' and 'must not'
- A single text field for a value to match against
- Saves as a json blob

Dev notes:
* Add additional is a separate story (stretch goal)
* Fields are some sort of composite
* Saved in a JsonField
* CallToAction in banner-block is a similar json field

[Styleguide](https://projects.invisionapp.com/dsm/silver-stripe/silver-stripe/asset/components/5bc3cd2e846a5a0011026c0e)

**Comment by brynwhyman** [comment]
There might be something provided with reactstrap that may provide this out of the box, will be dependant on how this aligns with designs though:
https://reactstrap.github.io/components/input-group/#Buttons--Dropdowns

cc @sachajudd

**Comment by sachajudd** [comment]
cc @clarkepaul

**Comment by clarkepaul** [comment]
All of the components used in the design should be available in basic Bootstrap components (select, field, button), I don't think we need anything fancy but if you find something which works better from the components them we'd be happy to use them.

**Comment by brynwhyman** [comment]
> Will be rendered in [the modal popup for a DataColumn's details](https://github.com/silverstripe/silverstripe-ckan-registry/issues/22)

This won't necessary be the case for the first round of development. Priority will be for this to be used in a GridField detail form first.

**Comment by robbieaverill** [comment]
PR ready for review at #49
