### ISSUE TITLE
Add CKANDataFilter models and GridField

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-ckan-registry#24]
**Not to be confused with #23**

Relationship: `has_many` on a [CKANRegistryPage](https://github.com/silverstripe/silverstripe-ckan-registry/issues/19). Versioning doesn't matter at this point.

## Generic fields

* Type (e.g. checkbox, text, dropdown) - note that the type should really be dictated by being a subclass of `CKANDataFilter`, e.g. `TextFilter`, `DropdownFilter` etc.
* Label (text)
* Column source(s) - kind of like a StringTagField from tag-field module (won't work with React right now). Columns are [CKANDataColumn models](https://github.com/silverstripe/silverstripe-ckan-registry/issues/20)
* All columns (bool)

### Text filter fields

* Nothing special

### Dropdown filter fields

* [Presented options (some sort of composite field - for now, JSON blob)](https://github.com/silverstripe/silverstripe-ckan-registry/issues/25)

Note that "All columns" would make "column sources" irrelevant.

### Checkbox filter fields

* Nothing special

[Styleguide](https://projects.invisionapp.com/dsm/silver-stripe/silver-stripe/asset/components/5bc50dab5fac6b001175391f)

**Comment by ScopeyNZ** [comment]
I think @NightJar has started on this?

**Comment by NightJar** [comment]
Oh, yes sorry. Forgot my "face" on it.

**Comment by NightJar** [comment]
Partially addressed in #36

**Comment by robbieaverill** [comment]
#36 is merged
