### ISSUE TITLE
Create React component for "Presented options" in a DropdownFilter

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-ckan-registry#25]
Requires #24

From #24 we can assume that the data type will be a JSON blob.

The field should have two radio options:

* "Select from all options"
* "Manually add options"
 
[Styleguide](https://projects.invisionapp.com/dsm/silver-stripe/silver-stripe/asset/components/5bd26ef841dbd50011d50eac)

### Select from all options

* Shows a scrollable container with a list of checkboxes representing each (? @sachajudd where do the values of this list come from?)
* Adds a "delimiter field"
  * Text input field
  * Attached "Update button" in an input group

### Manually add options

* Shows a textarea with right description
* Values would be entered one per line

**Comment by ScopeyNZ** [comment]
> where do the values of this list come from?

We can do a distinct query on that column through the CKAN API, akin to: ```SQL
SELECT DISTINCT value FROM ckan WHERE column = ?
```

**Comment by robbieaverill** [comment]
Completed in https://github.com/silverstripe/silverstripe-ckan-registry/pull/69
