### ISSUE TITLE
"Add filter" button for Filters GridField

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-ckan-registry#28]
Requires #24 

[Styleguide](https://projects.invisionapp.com/dsm/silver-stripe/silver-stripe/asset/components/5bc3cd2e846a5a0011026c0d)

* Could use a dropdownfield 
* dropdown options direct to GridField detail form, not a modal
* ~Could maybe use a PopoverOptionSet~
* The options will be PHP implementations of `CKANFilter` or similar (#24)

**Comment by brynwhyman** [comment]
To save time, let's look at the boostrap out of the box dropdown with @sachajudd

**Comment by robbieaverill** [comment]
Done with #51
