### ISSUE TITLE
InvalidArgumentException on save CKAN Registry Page with wrong "Successful" message on client side.

### ISSUE THREAD

**Issue by sabina-talipova** [silverstripe/silverstripe-ckan-registry#280]
### Description

When user saves CKAN Registry Page he gets "Saved 'New CKAN Registry Page' successfully." message, but highlighted as error (has ".toast--error" class). It happens since Back end returns Exception on "Save" request with the following message :
```
[Emergency] Uncaught InvalidArgumentException: Invalid sort column "CKANResourceField"."Position"
```

![SS_ckan.png](https://images.zenhubusercontent.com/6240ee9a7a0aac6d45cfd39d/f556a127-4a01-4b1a-ac88-e725ef253628)

After that page is broken and user cannot open it again.

### Steps to reproduce issue

- I go to "/admin/pages"
- I press the "Add new" button
- I select the "CKAN Registry Page" radio button
- I fill in "Page name" with "My CKAN Registry Page" 
- I press the "Save" button
- **I should see a "Saved" success toast** _(Right green message)_
- I click the "Data" CMS tab
- I fill in "DataResource-uri" with "https://catalogue.data.govt.nz/dataset/directory-of-educational-institutions"
- I wait for 5 seconds
- I should see "Early Childhood Services (ECE) Directory"
- I select "New Zealand Schools" from the ".ckan-resource-locator__resource-select select" field
- I wait for 5 seconds
- I press the "Save" button
- **I should see a "Saved" success toast** _(Exception with Successful message and error style)_

### AC's
- [ ] Page is saved successfully
- [ ] Toast style matches state.
- [ ] No exceptions are thrown.

Stretch goal
- Adjust the logic so failure are detected.

### PR's

**Comment by GuySartorelli** [comment]
This will probably be fixed as a part of https://github.com/silverstripeltd/product-issues/issues/644 - but I'll leave it open until I'm sure.

**Comment by sabina-talipova** [comment]
I've done a few tests and it looks like was already fixed. No any other issues happened.
I close this task as no longer existing.
