### ISSUE TITLE
Add frontend templates for CKANRegistryPage, including filter facets and controller handler to filter

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-ckan-registry#29]
Requires #19 

Designs: https://projects.invisionapp.com/share/8GOKGM7BTR5#/screens/327584755

![image](https://user-images.githubusercontent.com/5170590/49454298-c5e84700-f7dc-11e8-8dd1-6cfec1b9b5e1.png)

To confirm whether we need to use React for this (cc @brynwhyman)

* Templates
* Accessible markup
* Customisable CSS classes
* Controller action to handle the filter form
* Filters are generated from CKANFilter models defined on the page (has_many) see https://github.com/silverstripe/silverstripe-ckan-registry/issues/5 and https://github.com/silverstripe/silverstripe-ckan-registry/issues/24

**Comment by robbieaverill** [comment]
Sorry, duplicate of #4

**Comment by brynwhyman** [comment]
@robbieaverill I think we should open this again to focus on building the front end template. 
#4 is a sub-task to create a keyword search
#5 is a sub-task to add the filters created by the CMS user here: https://projects.invisionapp.com/share/8GOKGM7BTR5#/screens/325469914

**Comment by robbieaverill** [comment]
All done
