### ISSUE TITLE
PHP tests for ResourceLocatorField

### ISSUE THREAD

**Issue by NightJar** [silverstripe/silverstripe-ckan-registry#35]
_Originally posted by @NightJar in https://github.com/silverstripe/silverstripe-ckan-registry/pull/32#issuecomment-446089578_

This PR was getting long and was needed for other work to proceed (the Page type relates to the model info where field data will be saved - thus the models need this PR to be brought into existence without some nasty rebasing or merge conflicts).

In the very least, the hook for updating the save target should have some form of integration test. Please remember to mark said test with `@group integration` or whatever the PHPUnit notation for grouping is :)

**Comment by robbieaverill** [comment]
PR at #56
