### ISSUE TITLE
Validation of resource loader input

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-ckan-registry#37]
Validation could be enhanced. Sometimes validation isn't coming up when it should be?

To elaborate on....

**Comment by ScopeyNZ** [comment]
I have prepared a patch that addresses this in more detail: #39. Do you want to go through this together and see if it's suitable?

**Comment by ScopeyNZ** [comment]
Confirmed with @brynwhyman that it's resolved with #39 which has been merged now 🙂
