### ISSUE TITLE
Resource loader component should not display a validation error state on first load

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-ckan-registry#46]
When you load the page the resource loader component displays a validation error state until it has loaded the CKAN API data:

![image](https://user-images.githubusercontent.com/5170590/49968180-f5096180-ff1c-11e8-9153-4ae2dc18a342.png)

It shouldn't

**Comment by brynwhyman** [comment]
This will be a quick win. Moving to the backlog

**Comment by NightJar** [comment]
Sorry, to be clear @ScopeyNZ and I were talking yesterday and he thought he may have addressed it as part of #69 - but wasn't sure. I pinged as a reminder for later :)

**Comment by ScopeyNZ** [comment]
No it's not addressed. I noticed it while demo-ing today. It happens _extremely_ briefly - we're talking milliseconds here.

**Comment by robbieaverill** [comment]
PR for consideration at https://github.com/silverstripe/silverstripe-ckan-registry/pull/187

**Comment by ScopeyNZ** [comment]
Closed in #187
