### ISSUE TITLE
Column model Order should be "Presented order" and show the total number of columns

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-ckan-registry#47]
Current state:

![image](https://user-images.githubusercontent.com/5170590/49968538-fe46fe00-ff1d-11e8-871c-448a90930b9b.png)

Should be:

![image](https://user-images.githubusercontent.com/5170590/49968547-069f3900-ff1e-11e8-872b-ae2008fa1578.png)

Question for @clarkepaul @sachajudd: if you change the number to 32, should the other models be updated to adjust their own sort orders? E.g. whatever had 32 is changed to 31?

**Comment by NightJar** [comment]
>if you change the number to 32, should the other models be updated to adjust their own sort orders? E.g. whatever had 32 is changed to 31?

They will be currently as the widget in use for this functionality is `GridFieldOrderableRows` from `symbiote/silverstripe-gridfieldextensions` which does this by default, as I recall.
