### ISSUE TITLE
When clicking on a Column in the GridField, the CMS fields should be displayed in a settings GridField detail form

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-ckan-registry#48]
Requires #20

**This has replaced #22 which would implement this in a modal popup**

When clicking on the GridField row for a column, the user should be redirected to a GridField detail form to alter the display settings for each column.

- If the GridField is dirty (from inline edited checkboxes) then we may need to save those records before redirecting to the settings detail form. (Or do we just present the unsaved changes dialog?)
- Uses the results conditions filter component implemented in #23 

Designs
- CMS fields outlined here: https://projects.invisionapp.com/share/8GOKGM7BTR5#/screens/325469913

**Comment by robbieaverill** [comment]
This is the default behaviour so there's nothing to do. I'm going to close it, feel free to reopen if you think I've missed something.
