### ISSUE TITLE
Drill down into result for a detailed page view

### ISSUE THREAD

**Issue by rupachup** [silverstripe/silverstripe-ckan-registry#6]
## User story
As a register searcher that has found the record I want
I can get a view of that record by itself
So that I can get a more full set of data.

## Acceptance criteria

- [ ] User can click a result item to enter a detailed view
- [ ] The view shows the selected information for 'detail view' for that entry in the register even if columns were hidden in the search results view.
- [ ] There is a default style for this that works with the CWP starter theme
- [ ] The view is style-able by a developer if needed to be integrated into a sites layout and brand.
- [ ] (dependant on #79) There is a URL to view this detail view that user could send someone and they would see the same detail page.
- [ ] (dependant on #79) User can click back (either in browser or in the UI) to go back to the results view they came from (supporting exploration)

### Notes:
**Paul:** It would be good to get an example from one of the sites as to what this page might need to contain (screenshot)—I presume something already exists along these lines.

**Guy:** We didn't really go over this too much in the workshop. Are there any examples like what Paul was asking? Cam do you have any sketches about what you expected the backend flow would be?

**Comment by robbieaverill** [comment]
Dev consideration: the URL - should it be something like `/ckan-registry-page-url-here/item/UNIQUE-ID-HERE` ?
