### ISSUE TITLE
React component naming consistency

### ISSUE THREAD

**Issue by NightJar** [silverstripe/silverstripe-ckan-registry#66]
In PHP we have namespaces, which makes it easy to see where a particular class comes from and what it is intended for.
However in JavaScript we have no such separation, resulting in confusion in similarly named components.

As per point 3 in #57

@robbieaverill 
>* React component naming: We have called our PHP FormFields SomeField and the React component Some. We might want to rename the React components to have Field on the end too.
>* CKANResourceLoader component: the other components don't have the CKAN prefix. Should we add it to the other two, or remove it from this one?

@ScopeyNZ 
>* Happy to add Field. Makes sense to me.
>* Yeah this was a hard one when I named it. PHP has namespaces which makes it easy. SilverStripe\CKAN\Thing. JS is harder considering there's no namespacing with JS injector. I named the component I created CKANResourceLoader because I felt like that was the name I'd register with JS injector - it doesn't have to be though. I'd vote for some consistency here - I don't know what's the right way though

Outcome:
* Append `Field` to the name of components that implement views of `FormField`s
* >OK, let's rename the other two components to CKAN

**Comment by robbieaverill** [comment]
PR at https://github.com/silverstripe/silverstripe-ckan-registry/pull/77
