### ISSUE TITLE
Update CMS field labels to match designs for CKAN-Registry representation

### ISSUE THREAD

**Issue by NightJar** [silverstripe/silverstripe-ckan-registry#67]
The core of the CKAN configuration to fetch and manage API requests was developed to be agnostic of view, and to this end uses generic language when describing the configuration data to store. The intention was always to abstract this to a central CKAN interface/configuration module that many different 'view' implementations could rely upon, such as the `Registry` type interface we're building first (now - this repository), but also future will see things such as map interfaces being built (#9). For this reason we should not dive in renaming all the data fields or setting their labels outright to be in line with this module (registry), but we _should_ set the labels of these fields _for this module's CMS interface_ so they match the designs.

E.g.
https://projects.invisionapp.com/share/8GOKGM7BTR5#/screens/325469913
https://projects.invisionapp.com/share/8GOKGM7BTR5#/screens/325695108
https://projects.invisionapp.com/share/8GOKGM7BTR5#/screens/325695108

**Comment by robbieaverill** [comment]
PR at #78. I've made a PR in framework to change the default scaffolded field labels from "My Field Name" to "My field name" too. If accepted it'll be part of SilverStripe 4.4 though, so the logic I've added into this module to do the same thing for some of our fields is marked with comments referencing the framework issue to be removed at a time where 4.4 or newer is required.
