### ISSUE TITLE
CMS User can define how a category type filter gets it's values

### ISSUE THREAD

**Issue by rupachup** [silverstripe/silverstripe-ckan-registry#7]
## User story
As a CMS user, I can add a category filter to a register search page.
I have the flexibility to configure the filter to extract it's available values from the dataset, so that I can deal with the different ways categories might be expressed in datasets.

## Acceptance criteria

- [x] CMS User can set that category filters extra extracted from delimter separated categories stored in 1 column on a row in a dataset.
- [x] CMS User can set that a unique set of values is extracted from 1 Column over multiple rows (1 value per cell/distinct set).
- [x] CMS User can provide a name for this filter to be supplied to the end user.
- [x] CMS user can add multiple category filters to the available filters for the end user (use case is having both categories and tags stored against the dataset or similar).
- [x] Nice to have: provide a known manual set of categories in case they aren't extractable.

## Examples
Due to the complex nature of this examples of the potential source datasets will be provided.

**Guy:** I'm a little concerned about A/C 1 (delimter separated categories stored in 1 column). A/C 2 mentions the method of getting options by using a distinct search query, but there's not something so easy for the former? We can chat more about this on Thursday...

**Cam:** Sounds good. We don't control the shape of the data so we need a way to deal with extracting different sets of values to populate filters. I'm suggesting we tackle 2 options here but do it in a way that we could add other options later.

**Cam:** The two stakeholders we have have data categories in 2 forms we will need to cater for...

MSD has this format: https://uat.data.govt.nz/api/3/action/datastore_search?resource_id=440de418-d11c-42cb-b52c-2c8affe0ee70

(If an item is in many categories, then there is more than one row for the item).

We'll be able to use CKAN api DISTINCT to get this.

MPI has this format (comma separated categories).
https://www.foodsafety.govt.nz/registers-lists/animal-material-depot/index.htm?setup_file=animal-material-depot-ssi.setup.cgi&rows_to_return=20000&submit_search=Search

(I'll put up a test dataset verison of this to play with on our UAT server).

We may or may not be able to do something clever with the CKAN api to get this (note, there is a SQL like option for CKAN api queries otherwise we'll have to calculate on the SilverStripe end when someone configs in the CMS).

We can't control the data formats so we have to be able to be able to have some way to config extraction of categories/values to populate dropdowns.

Here's the example MPI dataset with comma separated categories.

https://uat.data.govt.nz/dataset/test-listed-animal-material-depots-search-results/resource/6c863a62-364f-4268-b6f6-90855dc14771

and api

https://uat.data.govt.nz/api/3/action/datastore_search?resource_id=6c863a62-364f-4268-b6f6-90855dc14771

This query should get you all the permutations for comma separated categories

https://uat.data.govt.nz/api/3/action/datastore_search?resource_id=6c863a62-364f-4268-b6f6-90855dc14771&fields=Animal%20Material%20Categories&distinct=True

Would then be a matter of extracting unique set from this.

**Guy:** Just playing around today Cam reviewing some initial designs and I'm trying to get an example of a date field from the API - using that UAT link you provided here. Seems as though the API has a bug with "timestamp" fields and distinct queries:

https://uat.data.govt.nz/api/3/action/datastore_search?resource_id=6c863a62-364f-4268-b6f6-90855dc14771&fields=Animal%20Material%20Categories,Listing%20Date&distinct=True

I just thought I'd raise that :) - PostgreSQL json type and array functions don't go so well together.

Remove the distinct and all is okay.

**Cam:** good to know, we are able to change the casting in CKAN for properties in APIs if that helps (just make the timestamp a string). Can probably raise that as an issue on CKAN open source too... seems like it should work.

**Comment by NightJar** [comment]
@ScopeyNZ and I have been talking about how and where people are expected to locate resources on an endpoint.
The mockups/wireframes all show website URLs as examples for packages, but these are very different from the API request points.
e.g. https://catalogue.data.govt.nz/dataset/family-services-directory
vs https://catalogue.data.govt.nz/dataset/api/3/action/package_show?id=family-services-directory
Where the latter then also requires POSTing, not GETing (thus cannot be tested in browser (easily).

One can get the resource endpoint directly by [opening a resource](https://catalogue.data.govt.nz/dataset/family-services-directory/resource/e86800a5-de8b-4842-8e73-043defffa742), then clicking the "Data API" button.
However the options contained within are very confusing, and one must look at the "Querying" examples to copy out the relevant portion (knowing to leave off the filters used in the examples). https://catalogue.data.govt.nz/api/3/action/datastore_search?resource_id=e86800a5-de8b-4842-8e73-043defffa742

Compare this to our AU friends example:
https://data.sa.gov.au/data/dataset/b1b64b79-e634-4c79-a52f-1680b3ef5c9c
where one can then click the "JSON" button and simply copy the URL from the opened tab: https://data.sa.gov.au/data/api/3/action/package_show?id=b1b64b79-e634-4c79-a52f-1680b3ef5c9c

This seems like a much nicer flow. Is it possible to expose this (package level JSON button) to our users?
As the alternative is that we do some intense parsing of supplied URIs, which will rely on assumptions and luck for the most part (never ideal).

**Comment by robbieaverill** [comment]
Any thoughts here @camfindlay?

**Comment by camfindlay** [comment]
Also note, you dont have to put the api version number in the endpoint URL (though assume that's something configurable in the "Settings" by a CMS admin.

**Comment by camfindlay** [comment]
Are there any questions on this user story specifically? eg, the different cases of how we need to be able to extract a set of values for a dropdown from a data resource?

**Comment by NightJar** [comment]
Yeah sorry this might be the wrong issue to have posted on, it was just the one open with the example URLs which we used to try to ascertain the structure from.

**Comment by NightJar** [comment]
This is #69
