### ISSUE TITLE
Render registry table with correct column headers

### ISSUE THREAD

**Issue by NightJar** [silverstripe/silverstripe-ckan-registry#71]
Present a data table to the end user on the website front-end regardless of data to populate it.

Configuration options coming from the CMS should allow for basic structure, as one can at least know the column header ahead of time.

This will involve selecting a react component to display this - be it custom built or using something like Griddle.js

**Comment by NightJar** [comment]
Assumptions made:
We will be exposing data to the component via a JSON attribute in the HTML block used to host the component.

Justification:
There isn't much need for an API for configuration, as it should never change (in terms of page lifetime).

**Comment by robbieaverill** [comment]
There's an example of using external API data in Griddle here: http://griddlegriddle.github.io/Griddle/examples/controlling-griddle/ under the "API Example" heading ([I can't deep link this](https://github.com/GriddleGriddle/griddle-docs/issues/23)).

**Comment by camfindlay** [comment]
I'm liking what I am seeing with Griddle... seems it can do maps and list views also which helps solve some future user stories ;)

**Comment by NightJar** [comment]
It turns out Griddle uses keyed data results to render it's own headers - so while #122 is intended to close this, it does not render headers. This is why.
