### ISSUE TITLE
Create filter container for front end presentation of filters

### ISSUE THREAD

**Issue by NightJar** [silverstripe/silverstripe-ckan-registry#73]
In order to allow end-users to select filters to apply to the registry table (#72) we need to present the filter options to them.
As there can be many, this makes sense to be able to group them in a list. This list may or may not be in charge or providing the "filter-spec" using the contained filter values.

Designs: https://projects.invisionapp.com/dsm/silver-stripe/silver-stripe/asset/components/5c09c9d18e1f85001158544f

**Comment by camfindlay** [comment]
Quick question about the filter block, assume this will be held in a SS template for the ckan registry page type? Would this mean a dev would be able to reposition the filter block in their markup at all? Say if they wanted to put filter on the right or at top?

**Comment by robbieaverill** [comment]
@camfindlay it's likely that the whole frontend area will be one React app, so devs would need to either use CSS to reposition the filter container or copy and modify the example app we'll ship with this module

**Comment by camfindlay** [comment]
In that case I assume the markup involved will be very generic then?

**Comment by robbieaverill** [comment]
Yeah should be. We'll built it in a way that you could float the filters to the right with CSS if you wanted to

**Comment by camfindlay** [comment]
Sweet, I have a new potential user of this feature once it's released that might need to position filters above the grid (probably just 1 dropdown and 1 text filter). Can you see if this can be factored in the way the markup and styles are fitted together? :)

**Comment by ScopeyNZ** [comment]
We also will encourage that people just copy the source of the React stuff if they want to do heavy modifications. This should be fairly easy to use from a developer perspective. I'm envisioning something like:

```
<div>
	<Filters {...props} />
	<Table {...props} />
</div>
```

So if you want to reorder them with this method (rather than CSS) you can just swap the position of those two React components. We should be mindful of creating appropriate docs.
