### ISSUE TITLE
Category filter

### ISSUE THREAD

**Issue by rupachup** [silverstripe/silverstripe-ckan-registry#8]
## User story
A a register searcher
I want to be able to select a category
So that the results returned are more relevant to my needs.

## Acceptance criteria

- [ ] User can select 1 category it will be passed in the query.
- [ ] Results can be refined by selecting a category and providing no keyword
- [ ] There is an appropriate UI element to select the categories (dropdown initially, but other options could be added later)
- [ ] Categories are set in the CMS by a CMS admin (there is a separate user story for this but could combine).

I suspect this type of filter could deal with things like boolean values in a column in a dataset... TRUE and FALSE would just be treated like 2 categories. So there is value in being able to add more than 1 of this filter type. Means filter types are probably more about how the end user interacts with then than the type of data involved.

Aim for dropbox for first implementation. We can carve off other UI options for future versions. @guymarriott2 I've updated the ACs accordingly which might impact you size.

**Comment by NightJar** [comment]
Front end component to the #69 back end configuration

**Comment by camfindlay** [comment]
close.
