### ISSUE TITLE
Set default ckan endpoint to demo + update CWP config

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-ckan-registry#80]
- [x] [The default endpoint should be set as: demo.ckan.org](https://github.com/silverstripe/silverstripe-ckan-registry/pull/105)
- [x] For CWP specific users, we'll [enable cwp config to set it to catalogue.data.govt.nz](https://github.com/silverstripe/cwp/pull/170
) --we'll raise this on the cwp-core repo, or a data recipe bundle if we get round to creating this.

**Comment by brynwhyman** [comment]
>when would you like this module to ship with CWP? That would dictate which version we add this configuration into

@robbieaverill the feature freeze for the upcoming CWP release is on 1 Feb - let's see how we go with module development over the next week or so and then make a call. At this stage I'm expecting we can include it in the upcoming release.

**Comment by robbieaverill** [comment]
Cool, in that case we'd ship with SilverStripe 4.3 as a minimum, which would mean we can add the configuration into **CWP 2.2**. Having the configuration without the module is harmless, and I assume this will be an opt-in module anyway

**Comment by ScopeyNZ** [comment]
Merged the CWP PR.
