### ISSUE TITLE
Column header should reflect datasets title, remove unneeded components

### ISSUE THREAD

**Issue by sachajudd** [silverstripe/silverstripe-ckan-registry#81]
- [x] ["Columns" header above the gridfield should be the datasets title](https://github.com/silverstripe/silverstripe-ckan-registry/pull/91
)
- [x] [Remove the unneeded "Add resource field" button](https://github.com/silverstripe/silverstripe-ckan-registry/pull/88)
- [x] [Remove the unneeded grey line](https://github.com/silverstripe/silverstripe-ckan-registry/pull/89) (as the "Data source URL" & "Resource name" will be able to be collapsed by a button see #82)

Please refer to [designs](https://projects.invisionapp.com/d/main#/console/15673101/325469913/preview)

Current:
![image](https://user-images.githubusercontent.com/24258161/50809917-92fd1a00-136b-11e9-99b9-c029d4e8dacc.png)

**Comment by robbieaverill** [comment]
PR for the heading at #91. @ScopeyNZ @NightJar this involved a bit of a refactor, I hope it's not too offensive!
