### ISSUE TITLE
Add collapsable button for editing a data source

### ISSUE THREAD

**Issue by sachajudd** [silverstripe/silverstripe-ckan-registry#82]
"Data source URL" and "Resource name" should be able to be collapsed by a button see, [designs](https://projects.invisionapp.com/d/main#/console/15673101/325469913/preview).

Note: Also noticing some unusual padding around the search icon and the pagination. Once the collapsable button is added the search will be able to open underneath this.

**Comment by robbieaverill** [comment]
Labelling as a bug because we missed it during initial development

**Comment by robbieaverill** [comment]
PR at #106
