### ISSUE TITLE
Dragging functionality is lost when clicking gridfield options

### ISSUE THREAD

**Issue by sachajudd** [silverstripe/silverstripe-ckan-registry#83]
Dragging functionality is lost when clicking gridfield options such as "Readable name", "Name", "Type" etc. If someone could look into this if it's just a default action or an actual bug that'd be great 👍 

![image](https://user-images.githubusercontent.com/24258161/50810343-fa1bce00-136d-11e9-9063-6514afcb484a.png)

**Comment by robbieaverill** [comment]
I discussed this with @sachajudd offline and am going to close since it's expected behaviour, not a bug
