### ISSUE TITLE
Create icon for CKAN Registry Page type

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-ckan-registry#95]
With a new page type available as part of this module, it should have an icon to accompany it, when selecting to add the page type to your site.

Currently uses the default icon:
![image](https://user-images.githubusercontent.com/15868440/50867895-f04ba680-1411-11e9-8b97-dc1244367949.png)

**Comment by ScopeyNZ** [comment]
FYI there's an appropriate icon in the new icon set: https://projects.invisionapp.com/dsm/silver-stripe/silver-stripe/asset/icons/5b960387cfee9600172b7249

Not sure if there's a similar option currently. Probably makes sense to use whatever a registry page uses right now.

**Comment by robbieaverill** [comment]
I added that icon to test, it's a little out on the left hand side:

![image](https://user-images.githubusercontent.com/5170590/50887575-d8fdc080-13f3-11e9-80d1-884217a9d81a.png)

Related issue to allow using font icons for SiteTree icons: https://github.com/silverstripe/silverstripe-admin/issues/574. Currently we have to use images.

**Comment by robbieaverill** [comment]
Oh yeah, it's an SVG 🤦‍♂️PR incoming with adjusted margin

**Comment by robbieaverill** [comment]
> Probably makes sense to use whatever a registry page uses right now.

RegistryPage doesn't have its own icon yet

**Comment by brynwhyman** [comment]
Paused until the new site tree icons can make it to core, as per: https://github.com/silverstripe/silverstripe-ckan-registry/pull/102#issuecomment-452847066
