### ISSUE TITLE
Responsive design tweaks

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-ckan-registry#97]
Updates to improve the responsive view on a reduced screen:

- [x] The READABLE LABEL column should be visible at min-width
- [x] Remove the drag handle on mobile

**Comment by robbieaverill** [comment]
PR at https://github.com/silverstripe/silverstripe-ckan-registry/pull/188

**Comment by ScopeyNZ** [comment]
Closed in #188
