### ISSUE TITLE
Improve column Presented Order option

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-ckan-registry#98]
Currently (`1.0.x-dev`) updating the Presented Order in a column edit screen will not alter the order of other columns.

This creates duplicate ordering (i.e moving to '7' would mean there are now 2 columns with the order '7'.) This is okay if the user is looking for _relative ordering_, but it's not doing a full reorder it a way that will always make sense.

- [ ] At minimum, we should update the label from 'Presented Order' to 'Relative Order'
- [ ] Stretch goal: Add a reordering function on Save that reorders all columns based on any change made.

**Comment by robbieaverill** [comment]
I reckon we should just add the logic to reshuffle the other column values relative to what you enter when you change it, and do that now. We'd need to be careful that reordering via drag handle in the GridField doesn't cause this logic to run as well though, that would cause a double up of the logic

**Comment by ScopeyNZ** [comment]
PR @ #120
