### ISSUE TITLE
Implement warning to user before changing resources

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-ckan-registry#99]
Should a user update the Data source URL or Resource name, all existing data settings will be wiped on save. This is intentional, however there should be a warning to the user before the wipe is actioned.

- [ ] Altering the Data source URL or Resource name presents a warning/ browser dialog to the user that all information will be reset if proceeding

**Comment by brynwhyman** [comment]
We might want to think about scenarios where the master data source doesn't change, but just the resource does. In that case it could make sense to retain all previous column and filter settings, as it's likely the column headings are the same.

**Comment by ScopeyNZ** [comment]
> We might want to think about scenarios where the master data source doesn't change, but just the resource does. In that case it could make sense to retain all previous column and filter settings, as it's likely the column headings are the same.

This is not necessarily true although it is for our favourite example dataset: https://catalogue.data.govt.nz/dataset/family-services-directory .

Most cases the dataset has a range of varying resources that aren't necessarily the same data let alone the same format. Our current solution of culling everything is suitable I think, and there could be a separate follow up where we design some procedure that analyses the new and existing resources for changes to determine whether the existing column/filter configuration can be kept.

**Comment by robbieaverill** [comment]
Are we thinking about a simple browser dialog for now? We could also show a notice/warning message on the field you've changed in the resource locator field to let the user know that way, e.g.:

![image](https://user-images.githubusercontent.com/5170590/50889252-da30ec80-13f7-11e9-95f8-212e285d9648.png)

**Comment by brynwhyman** [comment]
@sachajudd what do you think of the above? I'd be in favour of a browser dialog (on Save?) for now. At the moment we're facing a bit of complexity with messaging under the resource locator field (#111 )

**Comment by sachajudd** [comment]
@robbieaverill if we were to add a notice/warning message on the field it would have to use an invalid description as that blue text wouldn't pass contrast standards and isn't a pattern used across the CMS. Possibly an alert at the top of the page could work as well but for now I'd agree we use a browser dialog @brynwhyman 🙂

**Comment by robbieaverill** [comment]
Browser dialog it is.

**Comment by robbieaverill** [comment]
PR at #126
